More error checking with better errors

diff --git a/include/common b/include/common
--- a/include/common
+++ b/include/common
@@ -14,7 +14,7 @@ function create_directory {
 	if [[ ! -d "${1}" ]]; then
 		mkdir -p ${1}
 		if [ ${?} -ne 0 ]; then
-			echo "  - failed to create directory ${1}"
+			echo "  ERROR: failed to create directory ${1}"
 			exit 1
 		fi
 	fi
@@ -24,7 +24,7 @@ function create_file {
 	if [[ ! -f "${1}" ]]; then
 		touch ${1}
 		if [ ${?} -ne 0 ]; then
-			echo "  - failed to create file ${1}"
+			echo "  ERROR: failed to create file ${1}"
 			exit 1
 		fi
 	fi
@@ -32,13 +32,15 @@ function create_file {
 
 function check_directory {
 	if [[ ! -d "${1}" ]]; then
-		echo "  - could not locate directory ${1}"
+		echo "  ERROR: could not locate directory ${1}"
+		exit 1
 	fi
 }
 
 function check_file {
 	if [[ ! -f "${1}" ]]; then
-		echo "  - could not locate file ${1}"
+		echo "  ERROR: could not locate file ${1}"
+		exit 1
 	fi
 }
 
