Use case statement for OS detection
Signed-off-by: Wynter Woods <zerotri@gmail.com>

diff --git a/include/os_detect b/include/os_detect
--- a/include/os_detect
+++ b/include/os_detect
@@ -5,29 +5,12 @@ GREP=${GREP:-grep}
 REQUIRED=( ${UNAME} ${GREP} )
 
 source check_required
-
-OUTPUT="$(uname -a)"
-
-echo "$OUTPUT" | grep Darwin > /dev/null
-DARWIN=$?
-
-echo $OUTPUT | grep Linux   > /dev/null
-LINUX=$?
-
-echo $OUTPUT | grep Windows > /dev/null
-WIN=$?
-
-OS=""
-
-if [ $DARWIN ] && [ $LINUX ] && [ $WIN ]; then
-  echo "  OS version could not be determined."
-  exit 1
-elif [ $DARWIN -eq 0 ]; then
-  OS="darwin"
-elif [ $LINUX -eq 0 ]; then
-  OS="linux"
-elif [ $WIN -eq 0 ]; then
-  OS="win"
-fi
-
-echo "$OS"
+case "$(uname)" in
+	Darwin) OS="darwin";;
+	Linux) OS="linux";;
+	MSYS32) OS="windows";;
+	*)
+		echo "  OS version not supported/could not be determined"
+		exit 1
+		;;
+esac
